### ISSUE TITLE
Проблема с отображением значка 

### ISSUE THREAD

**Issue by kokoss19** [JustOff/scriptlet-doctor#2]
Приветствую! Вчера после установления вашего дополнения, значок отображался на панели на панели навигации. Сегодня значок уже не отображается на панели навигации ( точнее сказать нигде ), но вроде работает, отключал все дополнения, но причина ни в этом, не могу понять в чём проблема. В чём может быть причина(проблема) ?

**Comment by JustOff** [comment]
Версия браузера? Ошибки в консоли (Ctrl+Shift+J) при выключении/включении дополнения?

**Comment by kokoss19** [comment]
Firefox esr 52

**Comment by JustOff** [comment]
Так, я кажется понял в чем дело, classic я писал под Pale Moon и забыл добавить кусок кода для старых фоксов, исправлю. В качестве аварийного решения - сбросить `extensions.scriptlet-doctor.bar` в `about:config` и выкл/вкл дополнение через `about:addons`.

**Comment by kokoss19** [comment]
Вот что выдаёт консоль после выключения/включения дополнения: Warning: attempting to write 6604 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 10043 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 6877 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 10042 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.

**Comment by JustOff** [comment]
> Вот что выдаёт консоль

Это норм, см. ответ выше.

**Comment by kokoss19** [comment]
После манипуляций в Конфиге, значок появился. Благодарю!

**Comment by JustOff** [comment]
Исправлено в версии [1.0.2](https://github.com/JustOff/scriptlet-doctor/releases/tag/1.0.2).
