### ISSUE TITLE
Проблема с установкой дополнения на FF 56.0.2

### ISSUE THREAD

**Issue by Eankun** [JustOff/scriptlet-doctor#3]
Приветствую! Собственно, сабж. При попытке установить scriptlet-doctor-classic-1.1.0.xpi со страницы релизов (или файл, сохранённый на ПК) фф выдаёт стандартную ругалку о том что расширение не было проверено.
https://i.imgur.com/s1nWn2M.png
Что я делаю не так? Спасибо.

**Comment by JustOff** [comment]
"Стандартная ругалка" лечится стандартным методом [отключения проверки цифровой подписи](https://forum.mozilla-russia.org/viewtopic.php?id=70326).

**Comment by Eankun** [comment]
Нихрена ж себе "стандартный метод", мне бы он и во сне не приснился.
Благодарю, расширение установилось.

**Comment by JustOff** [comment]
Вообще говоря странно, что вы используя старую версию браузера до сих пор не столкнулись с необходимостью установки неподписанных расширений. Какая у вас тогда версия uBlock Origin?

**Comment by Eankun** [comment]
1.25.2, буквально только что обновление приехало, кстати (до применения хака по ссылке выше).
https://i.imgur.com/6sNhPBB.png
Прочие расширения тоже вроде обновляются без проблем, хотя и нечасто.

**Comment by JustOff** [comment]
Хм, действительно, он до сих пор поддерживает 55+, к сожалению для Scriptlet Doctor (quantum) в таких старых Firefox не всего хватает, а подписать Scriptlet Doctor (classic) Mozilla уже давно не позволяет.
