### ISSUE TITLE
Проблема с Яндекс Диск

### ISSUE THREAD

**Issue by violinisten** [JustOff/scriptlet-doctor#4]
Здравствуйте.  
При включенном расширении не работает скачивание с yadi.sk (Яндекс Диск). Лечится это либо временным отключением расширения через кнопку либо удалением yandex.ru из списка доменов (что не выход). Возможно ли здесь реализовать "черный список" для доменов по выбору (в данном случае yadi.sk)?
Pale Moon 28.11.0
scriptlet-doctor 1.2.0

**Comment by JustOff** [comment]
На чистом профиле в Pale Moon 28.11.0 с установленным только Scriptlet Doctor по ссылке https://yadi.sk/d/KSeSuvCDmHG9Gw все отлично скачивается. Если проблема возникает после установки uBlock Origin, то с ней [сюда](http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&glp).

**Comment by violinisten** [comment]
Это мелкий файл, он его, видать, сразу заглатывает. Попробуйте, например, такой https://yadi.sk/d/XEeqVOE4y7X8BA
Да, на чистом профиле в Pale Moon 28.11.0 с установленным только Scriptlet Doctor.

**Comment by JustOff** [comment]
Тоже без проблем скачалось: logic-pro-x-10-5-user-guide.pdf - 74567949 байт.
Увы, пока не смогу воспроизвести - не смогу и исправить. И черный список не поможет, потому как yadi.sk не поддомен yandex.ru, т.е. Scriptlet Doctor там не активен с дефолтными настройками.

**Comment by violinisten** [comment]
Да, действительно, в конце концов скачивает, только при включенном Scriptlet Doctor почему-то не работает индикатор загрузки ("счетчик").  Это меня и сбило с толку, я качал файл в 1.5 Гига.
![Capture1](https://user-images.githubusercontent.com/13586456/88849611-cd9b0180-d1f2-11ea-896d-b127ab0f634f.PNG)
![Capture2](https://user-images.githubusercontent.com/13586456/88849640-d68bd300-d1f2-11ea-9804-67c86effd8a2.PNG)

**Comment by JustOff** [comment]
Исправил в [1.2.1](https://github.com/JustOff/scriptlet-doctor/releases/tag/1.2.1).

**Comment by violinisten** [comment]
Прекрасно! Спасибо.
