### ISSUE TITLE
docviewer.yandex.ru

### ISSUE THREAD

**Issue by dimisa-RUAdList** [JustOff/scriptlet-doctor#6]
Похоже, scriptlet-doctor-quantum нуждается в правках.
Перестали отрабатывать uBO-правила в просмотрщике яндекса.

**Конфигурация, при использовании которой повторяется проблема**
FF-quantum, любая версия.
uBlock Origin 1.30.4 default
+[RU AdList](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock%2Bcssfixes.txt&title=RU%20AdList%20for%20uBlock%20Origin)
+[Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)

**Как воспроизвести**
Зайти в почту яндекса (mail.yandex.ru), создать черновик письма, прикрепив к нему любой документ, например pdf, после чего попробовать его открыть. В результате откроется страница с адресом типа `https://docviewer.yandex.ru/view/*`, на которой соответствующие правила будут отброшены, а яндекс.директ пропущен.

**Comment by JustOff** [comment]
Подтверждаю, причину предварительно нашел, буду разбираться.
