### ISSUE TITLE
Add in the description where to add a domains

### ISSUE THREAD

**Issue by decembre** [JustOff/scriptlet-doctor#7]
Thanks for this addon!
It solve a problem with Flickr, uBlockOrigin and Waterfox Classic 56.3:
https://github.com/uBlockOrigin/uAssets/issues/7799#issuecomment-718400832

As you can read in my comment i have not understand that your addon as an option with a form where we need to add domains.
Maybe for your future users, you can add this precision, with a screenshot?

**Comment by krystian3w** [comment]
Scroll to right:

https://github.com/JustOff/scriptlet-doctor/blob/95547a3c42a5ed9aae52801d1b329aeeb8828444/README.md#L5

> `it is recommended to keep **Scriptlet Doctor** enabled only for a limited list of domains, as configured by default.`

**Comment by decembre** [comment]
Yes, i "carefully" read your description...
But don't understand "as configured by default" reference to an option where type these domains.
Just add a screenshot to your description:
With it, i understand my mistake and go to see if your addon as an option.
Before, after install it, i test to click on its icon, to see if a menu appear or something other

**Comment by JustOff** [comment]
Ok, I'll try to clarify the description to avoid existing ambiguities.

**Comment by decembre** [comment]
;-)
