### ISSUE TITLE
Problem on Flickr to help uBlockOrigin (with Waterfox Classic)

### ISSUE THREAD

**Issue by decembre** [JustOff/scriptlet-doctor#8]
I use your addon on Flickr to help uBlockOrigin (with Waterfox Classic)to block a nag screen:
" a message comes up with a 5 seconds timer before further navigation is allowed"
I have posted in uBlocOrigin issues:
[flickr.com #7799](https://github.com/uBlockOrigin/uAssets/issues/7799)

I have fill the option of your addon.
I seems worked fine, but now it fail..

Can you help me, this nag screen is very irritating...
TEST link:
[Yana Shmaylova](https://www.flickr.com/photos/chris_ong_photography/15213575497l) and navigate in the stream:
After 4 or 5 images the nag screen appear.

TEST In about:config:
Set on false "security.csp.enable" is not sufficient:
the nag screen apprear
I need to set False "security.csp.enableStrictDynamic" too:
here apparently, that's good.

**Comment by JustOff** [comment]
> [Yana Shmaylova](https://www.flickr.com/photos/chris_ong_photography/15213575497l) and navigate in the stream:

404
This is not the page you’re looking for.
2020-11-29T10:07:01Z-0573b5cd@server
Sorry, we don’t recognize this URL.

**Comment by decembre** [comment]
Ha...
Thanks for the reply and sorry for this wrong link.
Here an another link:
[portrait](https://www.flickr.com/photos/b58/50632276443)
And here just as text:
https://www.flickr.com/photos/b58/50632276443

But you can test by opening an image in Flickr and navigate in its author stream.

**Comment by JustOff** [comment]
> But you can test by opening an image in Flickr and navigate in its author stream.

Where is the author stream?

**Comment by decembre** [comment]
By example go to:
https://www.flickr.com/photos/b58/50632276443/in/photostream/
As you can see at the end, you are in a shot from the author stream:
/in/photostream/

Another way:
When viewing the shot, Click the Buddy icon of the user 
and choose on of 4 shots which appear in a popup. 
To navigate in the stream, use the arrows on the side of the shot.

Ps:
I retest it now and see no nag screen:
Strange, maybe it seems intermittent.
But i have often the problem.
I am not certain, but when i have many tabs open, the problem is more present.
Maybe sometime uBlockOrign or your script have not the time to catch the nag event before  it arrive?

But when the nag screen always appear (in some sessions that's always the case), 
if i set on False the about:config `"security.csp.enableStrictDynamic"`, solve the problem.

I hope that's more clear....

Here the nag screen:
![FLickr nag screen - 2020-11-29_122429](https://user-images.githubusercontent.com/868778/100540507-fcc38d00-323d-11eb-929a-3337a0dcd644.jpg)

**Comment by JustOff** [comment]
Try [scriptlet-doctor-classic-1.2.4b1.xpi.zip](https://github.com/JustOff/scriptlet-doctor/files/5612139/scriptlet-doctor-classic-1.2.4b1.xpi.zip) (rename xpi.zip to xpi) with Waterfox multi-process disabled (this is necessary because of the old Mozilla [bug 1261585](https://bugzilla.mozilla.org/show_bug.cgi?id=1261585)).

**Comment by decembre** [comment]
Thanks a lot!
Installed , i need to test it in the time to see if it always actif.....
Just by curiosity:
What's the change in the function?
PS:
Waterfox multi-process disabled:
Yes it was diabled since a long time

**Comment by JustOff** [comment]
> What's the change in the function?

```js
csp = csp.replace(/&#x27;/g, "'");
```
I've never seen this in the `http-equiv="Content-Security-Policy"` meta element before and didn't even know that it's allowed :stuck_out_tongue_winking_eye:

**Comment by decembre** [comment]
We learn all time something new:
that's fine!
Now, wait and see.
If that's good, i say it to you....

**Comment by decembre** [comment]
Well...
After few days of testing...
It seems solved!
Thank:
Fine work, very useful for me.

Ps;
about HTTP-Equiv (i don't fully understand (this damn CSP...) but maybe useful for you?)
[HTTP-Equiv: What Is It Used For?](https://www.keycdn.com/support/http-equiv)
